In [1]:
import numpy as np

### Numpy Indexing And Slicing Of Vectors

In [3]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
# same as list and array like in other langauges
arr[6]

np.int64(17)

In [6]:
arr[9]

np.int64(20)

In [9]:
# to print a sequence of number like from 11-16 we will be writing like this [starting index: ending index (n-1)]. By default the starting value is 0 so if we dont write anything on starting point it will assume 0 by default. And for the ending point if we leave that so by default the value will be the last index
arr[0:6]
arr[3::2] #will print from 14-20 ::-> means steps 

array([14, 16, 18, 20])

### Numpy Indexing And Slicing Of Matrix

In [11]:
#  lets create a 2d array using arrange function
arr_matrix = np.arange(1,31).reshape(6,5)
arr_matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [16]:
# if we will do the same way like we did for vectors it will print the complete row but to print an appropriate index like we have to print the number 2 we can write like this [row index it also starts from 0 the first one will be 0 and the second row will be 1 and it will be in the same,the index of the element in that appropriate row]
arr_matrix[0] # this will print the first row
arr_matrix[0,4] #this will print the 2nd element at index 1 in the first row 

np.int64(5)

In [20]:
# to print a elements from both column 1 and 2 we will be writing like this as below [column start point:endpoint of the second column remember n-1, then the element number u want to print from both column and then the end point of the second element remember n-1]
arr_matrix[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [23]:
arr_matrix[3:6,3:6]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
# now print the column number 3
arr_matrix[:,2]
# select the rows as u will be requiring all rows leaving that empty by default takes the start point and end point and after comma u will write the row u want to print from each column

array([ 3,  8, 13, 18, 23, 28])

### Boolean Indexing

In [30]:
# it refers to printing of only the specific numbers 
arr

array([12, 14, 16, 18, 20])

In [31]:
arr_bool = arr %2 == 0
arr_bool

array([ True,  True,  True,  True,  True])

In [32]:
arr = arr[arr_bool]
arr

array([12, 14, 16, 18, 20])