In [1]:
import numpy as np

**Valid Sudoku**

In [2]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [3]:
# we have to validate is it a valid sudoku or not
# for taking out sum of every row we will be using numpy addition
# for rows axis is 1 while for column is 0
sum_row = np.sum(s,axis = 1)
sum_row

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [4]:
sum_column = np.sum(s,axis = 0)
sum_column

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [5]:
# lets verify it too
b = np.sum(s,axis=1)
for i in b:
    if i != 45:        
        print("Sudoku Not Valid")
        break
else:
    print(f"For row it is valid")

For row it is valid


In [6]:
c = np.sum(s,axis = 0)
for i in b:
    if i != 45:
        print("Sudoku not valid")
        break
else:
    print("Not valid")

Not valid


In [7]:
block1 = s[0:3,0:3]
block1
block2 = s[0:3,3:6]
block2
block3 = s[0:3,6:9]
block3


array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [8]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())




45
45
45
45
45
45
45
45
45


**General Questions**

In [9]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [10]:
#Get the shape of the matrix.
data.shape
# 5 rows and 3 columns

(5, 3)

In [11]:
#Find the average age of students.
age = data[0:,0:1]
age
avg_age = np.average(age)
avg_age

np.float64(18.4)

In [12]:
#Extract Math marks of all students.
math = data[0:,1:2]
math

array([[85],
       [92],
       [76],
       [65],
       [90]])

In [13]:
#Find the highest Science mark.
science = data[0:,2:]
science
highest = np.max(science)
highest

np.int64(95)

In [14]:
#Get details of the student who scored more than 90 in Math.
detail = data[:,1] > 90
data[detail]


array([[19, 92, 88]])

In [15]:
#Increase Math marks of all students by 5.
math
increase = math + 5
increase

array([[90],
       [97],
       [81],
       [70],
       [95]])

In [16]:
#Find how many students are younger than 19.
age = data[0:,0:1]
age
younger = age < 19
age[younger]
len(age[younger])

3

In [17]:
#Calculate the average marks in each subject (column-wise mean).
data[:,1:3]
np.mean(data[:,1:3],axis = 0)
# column wise thing is axis = 0


array([81.6, 83.2])

In [18]:
#Get data of students who scored at least 80 in both subjects.
score = data[(data[:,1] >= 80) & (data[:,2] >= 80)]
score

array([[19, 92, 88],
       [20, 90, 85]])

In [19]:
#Replace all Science marks < 75 with 0.
data[0:,2][data[:,2] < 75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])